In [5]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import json

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
file = open("/content/drive/My Drive/coll bb_SortByConf.json")
data = json.load(file)
df = pd.DataFrame(data["teams"])

vaTeams = df.loc[df["state"] == "VA"]
mascotGrouped = df.groupby("name").count()
mascotGrouped = mascotGrouped.loc[mascotGrouped["tid"] > 1]

pd.set_option("display.max_rows", 100)
df.head(100)

,tid,cid,did,region,name,abbrev,pop,city,state,latitude,longitude
0,159,0,0,Boston College,Eagles,BC,161,Chestnut Hill,MA,42.330,-71.166
1,105,0,0,Clemson,Tigers,CLEM,215,Clemson,SC,34.678,-82.839
2,109,0,0,Florida State,Seminoles,FSU,211,Tallahassee,FL,30.442,-84.298
3,18,0,0,Louisville,Cardinals,UL,302,Louisville,KY,38.250,-85.766
4,31,0,0,North Carolina State,Wolfpack,NCST,289,Raleigh,NC,35.786,-78.682
5,9,0,0,Notre Dame,Fighting Irish,ND,311,South Bend,IN,41.672,-86.255
6,66,0,0,Syracuse,Orange,CUSE,254,Syracuse,NY,43.046,-76.144
7,141,0,0,Wake Forest,Demon Deacons,WAKE,179,Winston-Salem,NC,36.102,-80.260
8,0,0,1,Duke,Blue Devils,DUKE,320,Durham,NC,35.988,-78.907
9,145,0,1,Georgia Tech,Yellow Jackets,GT,175,Atlanta,GA,33.775,-84.394
10,47,0,1,Miami,Hurricanes,CANES,273,Coral Gables,FL,25.750,-80.271
11,8,0,1,North Carolina,Tar Heels,UNC,312,Chapel Hill,NC,35.933,-79.033
12,76,0,1,Pittsburgh,Panthers,PITT,244,Pittsburgh,PA,40.439,-79.976
13,6,0,1,Virginia,Cavaliers,UVA,314,Charlottesville,VA,38.030,-78.478
14,220,0,1,Virginia Tech,Hokies,VT,100,Blacksburg,VA,37.230,-80.417
15,90,0,1,Northeastern,Huskies,NEAST,230,Boston,MA,42.358,-71.063
16,62,1,2,Indiana,Hoosiers,IND,258,Bloomington,IN,39.162,-86.529
17,13,1,2,Maryland,Terrapins,MD,307,College Park,MD,38.997,-76.927
18,78,1,2,Michigan,Wolverines,MICH,242,Ann Arbor,MI,42.281,-83.748
19,14,1,2,Michigan State,Spartans,MSU,306,East Lansing,MI,42.734,-84.480
20,37,1,2,Ohio State,Buckeyes,OSU,283,Columbus,OH,39.983,-82.983
21,108,1,2,Penn State,Nittany Lions,PSU,212,University Park,PA,40.796,-77.862
22,179,1,2,Rutgers,Scarlet Knights,RUTG,141,New Brunswick,NJ,40.486,-74.444
23,213,1,2,IPFW,Mastodons,IPFW,107,Fort Wayne,IN,41.118,-85.109
24,77,1,3,Illinois,Fighting Illini,ILL,243,Champaign,IL,40.115,-88.272
25,39,1,3,Iowa,Hawkeyes,IOWA,281,Iowa City,IA,41.666,-91.533
26,100,1,3,Minnesota,Golden Gophers,MINN,220,Minneapolis,MN,44.980,-93.264
27,153,1,3,Nebraska,Cornhuskers,NEB,167,Lincoln,NE,40.810,-96.680
28,129,1,3,Northwestern,Wildcats,NW,191,Evanston,IL,42.046,-87.694
29,61,1,3,Purdue,Boilermakers,PUR,259,West Lafayette,IN,40.441,-86.912
30,1,1,3,Wisconsin,Badgers,WISC,319,Madison,WI,43.066,-89.400
31,256,1,3,IUPUI,Jaguars,IUPUI,64,Indianapolis,IN,39.774,-86.176
32,68,2,4,Florida,Gators,FLA,252,Gainesville,FL,29.652,-82.325
33,43,2,4,Georgia,Bulldogs,UGA,277,Athens,GA,33.950,-83.383
34,2,2,4,Kentucky,Wildcats,UK,318,Lexington,KY,38.029,-84.494
35,216,2,4,Missouri,Tigers,MIZZ,104,Columbia,MO,38.951,-92.328
36,96,2,4,South Carolina,Gamecocks,SCAR,224,Columbia,SC,34.029,-80.896
37,101,2,4,Tennessee,Volunteers,TENN,219,Knoxville,TN,35.972,-83.942
38,87,2,4,Vanderbilt,Commodores,VANDY,233,Nashville,TN,36.166,-86.783
39,319,2,4,South Carolina State,Bulldogs,SCSU,1,Orangeburg,SC,33.497,-80.850
40,79,2,5,Alabama,Crimson Tide,BAMA,241,Tuscaloosa,AL,33.206,-87.534
41,22,2,5,Arkansas,Razorbacks,ARK,298,Fayetteville,AR,36.076,-94.160
42,131,2,5,Auburn,Tigers,AUB,189,Auburn,AL,32.597,-85.480
43,64,2,5,Louisana State,Tigers,LSU,256,Baton Rouge,LA,30.450,-91.140
44,56,2,5,Mississippi,Rebels,MISS,264,Oxford,MS,34.359,-89.526
45,214,2,5,Mississippi State,Bulldogs,MSST,106,Starkville,MS,33.462,-88.820
46,67,2,5,Texas A&M,Aggies,TAMU,253,College Station,TX,30.601,-96.314
47,128,2,5,NC-Central,Eagles,NCCENT,192,Durham,NC,35.974,-78.898
48,92,3,6,California,Golden Bears,CAL,228,Berkeley,CA,37.871,-122.272
49,26,3,6,Oregon,Ducks,ORE,294,Eugene,OR,44.051,-123.086
50,132,3,6,Oregon State,Beavers,OREST,188,Corvallis,OR,44.566,-123.283
51,33,3,6,Stanford,Cardinal,STAN,287,Stanford,CA,37.430,-122.170
52,119,3,6,Washington,Huskies,WASH,201,Seattle,WA,47.609,-122.333
53,160,3,6,Washington State,Cougars,WASHST,160,Pullman,WA,46.733,-117.166
54,232,3,6,Denver,Pioneers,DENV,88,Denver,CO,39.678,-104.962
55,25,3,6,San Diego State,Aztecs,SDST,295,San Diego,CA,37.215,-117.162
56,3,3,7,Arizona,Wildcats,ARIZ,317,Tucson,AZ,32.221,-110.926
57,89,3,7,Arizona State,Sun Devils,ASU,231,Tempe,AZ,33.429,-111.943
58,117,3,7,Colorado,Buffaloes,COLO,203,Boulder,CO,40.027,-105.251
59,38,3,7,UCLA,Bruins,UCLA,282,Los Angeles,CA,34.050,-118.250
60,196,3,7,USC,Trojans,USC,124,Los Angeles,CA,34.050,-118.250
61,12,3,7,Utah,Utes,Utah,308,Salt Lake City,UT,61.218,-149.900
62,36,3,7,Colorado State,Rams,COLOST,284,Fort Collins,CO,40.559,-105.078
63,45,3,7,Boise State,Broncos,BOISE,275,Boise,ID,43.616,-116.200
64,16,4,8,Baylor,Bears,BAYL,304,Waco,TX,31.551,-97.155
65,15,4,8,Iowa State,Cyclones,IOWAST,305,Ames,IA,42.034,-93.620
66,4,4,8,Kansas,Jayhawks,KU,316,Lawrence,KS,38.971,-95.235
67,107,4,8,Kansas State,Wildcats,KSU,213,Manhattan,KS,39.191,-96.591
68,19,4,8,Oklahoma,Sooners,OKLA,301,Norman,OK,35.220,-97.440
69,55,4,8,Valparaiso,Crusaders,VALPO,265,Valparaiso,IN,41.463,-87.043
70,59,4,8,Green Bay,Phoenix,UWGB,261,Green Bay,WI,44.513,-88.015
71,127,4,8,Cleveland State,Vikings,CLEVST,193,Cleveland,OH,41.501,-81.675
72,58,4,9,Oklahoma State,Cowboys,OKLAST,262,Stillwater,OK,36.115,-97.058
73,134,4,9,TCU,Horned Frogs,TCU,186,Fort Worth,TX,32.757,-97.333
74,50,4,9,Texas,Longhorns,TEXAS,270,Austin,TX,30.250,-97.750
75,183,4,9,Texas Tech,Red Raiders,TT,137,Lubbock,TX,33.566,-101.883
76,21,4,9,West Virginia,Mountaineers,WVU,299,Morgantown,WV,39.633,-79.950
77,169,4,9,Oakland,Golden Grizzlies,OAK,151,Rochester,MI,42.672,-83.215
78,207,4,9,Milwaukee,Panthers,UWMIL,113,Milwaukee,WI,43.075,-87.882
79,205,4,9,Detroit,Titans,DET,115,Detroit,MI,42.414,-83.137
80,53,5,10,Georgia State,Panthers,GAST,267,Atlanta,GA,33.755,-84.390
81,123,5,10,Louisiana Monroe,War Hawks,ULM,197,Monroe,LA,32.509,-92.118
82,177,5,10,UT-Arlington,Mavericks,UTARL,143,Arlington,TX,32.705,-97.122
83,269,5,10,South Alabama,Jaguars,SOALA,51,Mobile,AL,30.694,-88.043
84,231,5,10,Texas State,Bobcats,TEXST,89,San Marcos,TX,29.879,-97.938
85,310,5,10,Troy,Trojans,TROY,10,Troy,AL,31.808,-85.970
86,264,5,10,Elon,Phoenix,ELON,56,Elon,NC,36.107,-79.501
87,301,5,10,Charleston,Cougars,CHAR,19,Charleston,SC,32.783,-79.933
88,110,5,11,Georgia Southern,Eagles,GASO,210,Statesboro,GA,32.445,-81.779
89,121,5,11,Louisiana Layayette,Ragin' Cajuns,LALAF,199,Lafayette,LA,30.216,-92.033
90,241,5,11,Appalachian State,Mountaineers,APPST,79,Boone,NC,36.211,-81.668
91,274,5,11,Arkansas-Little Rock,Trojans,UALR,46,Little Rock,AR,34.736,-92.331
92,276,5,11,Arkansas State,Red Wolves,ARKST,44,Jonesboro,AR,35.828,-90.694
93,150,5,11,UNC-Wilmington,Sweahawks,NCWILM,170,Wilmington,NC,34.226,-77.878
94,308,5,11,UNC-Greensboro,Spartans,UNCG,12,Greensboro,NC,36.069,-79.811
95,300,5,11,Jacksonville State,Gamecocks,JVILLE,20,Jacksonville,AL,33.815,-85.760
96,72,6,12,Eastern Washington,Eagles,EWASH,248,Cheney,WA,47.488,-117.578
97,139,6,12,Sacramento State,Hornets,SACST,181,Sacramento,CA,38.555,-121.468
98,239,6,12,Northern Colorado,Bears,NOCOL,81,Greeley,CO,40.416,-104.716
99,266,6,12,Idaho,Vandals,UI,54,Moscow,ID,46.730,-117.000

In [44]:
print(f"\nNumber of teams: {len(df.index)}")
print(f"Number of teams in Virginia: {len(vaTeams.index)}")
print(f"Teams grouped by duplicated mascot: \n\n {mascotGrouped['tid'].to_string()}")

Number of teams: 320
Number of teams in Virginia: 13
Teams grouped by duplicated mascot:

 name
49ers             2
Aggies            4
Bears             4
Bison             2
Bisons            2
Bobcats           3
Broncos           3
Bruins            2
Buccaneers        2
Bulldogs         13
Bulls             2
Cardinals         4
Catamounts        2
Colonials         2
Cougars           4
Cowboys           3
Crusaders         2
Dukes             2
Eagles           10
Falcons           2
Gaels             2
Gamecocks         2
Golden Eagles     4
Hawks             4
Highlanders       2
Hornets           3
Huskies           5
Jaguars           3
Knights           2
Lions             2
Lumberjacks       2
Mavericks         2
Mountaineers      3
Mustangs          2
Owls              4
Panthers          8
Phoenix           2
Pioneers          2
Pirates           3
Raiders           2
Rams              4
Rebels            2
Redhawks          3
Roadrunners       2
Spartans          4
Terriers          3
Tigers            9
Titans            2
Trojans           3
Vikings           3
Wildcats          8
Wolverines        2